// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-QVwSy-QJGfZ5eXrWW-XMqx2YowN2U9U',
    appId: '1:360191431085:web:d60a2c28f77a5603901124',
    messagingSenderId: '360191431085',
    projectId: 'fir-project-4b379',
    authDomain: 'fir-project-4b379.firebaseapp.com',
    storageBucket: 'fir-project-4b379.appspot.com',
    measurementId: 'G-ZMR23Z3E55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ2gGT6AlDuwxrgded3jHy8D9k-_mJI7U',
    appId: '1:360191431085:android:35d0bd93c2e7591b901124',
    messagingSenderId: '360191431085',
    projectId: 'fir-project-4b379',
    storageBucket: 'fir-project-4b379.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCksYPK21YyX-OBrBgBskpOp8AAV-5_8C0',
    appId: '1:360191431085:ios:251284be604abd54901124',
    messagingSenderId: '360191431085',
    projectId: 'fir-project-4b379',
    storageBucket: 'fir-project-4b379.appspot.com',
    iosBundleId: 'com.example.firebaseproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCksYPK21YyX-OBrBgBskpOp8AAV-5_8C0',
    appId: '1:360191431085:ios:c25b4ee1c2840ae8901124',
    messagingSenderId: '360191431085',
    projectId: 'fir-project-4b379',
    storageBucket: 'fir-project-4b379.appspot.com',
    iosBundleId: 'com.example.firebaseproject.RunnerTests',
  );
}
